#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################

# This workflow executes several linters on changed files based on languages
# used in your code base whenever you push a code or open a pull request.
#
# You can adjust the behavior by modifying this file.

#
# Documentation:
#
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
# https://github.com/github/super-linter
# https://github.com/marketplace/actions/super-linter
# https://github.com/github/super-linter/wiki
#

name: Lint Code Base

#########################################
## CONTROLS WHEN THE WORKFLOW WILL RUN ##
#########################################

on:
  # Triggers the workflow on push or pull request events, but only for the
  # main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


###############################################################################
################################ SET THE JOB ##################################
###############################################################################

# A workflow run is made up of one or more jobs that can run sequentially or in
# parallel
jobs:
  # This workflow contains a single job called "run-lint"
  run-lint:
    # Set the agent to run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      # Run Linter against code base
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_PHP_PSALM: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: .*vendor/.*
